apiVersion: v1
kind: ServiceAccount
metadata:
  name: vas-platform-sa
  namespace: team-b
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vas-platform-role
  namespace: team-b
rules:
  - apiGroups: ["", "apps", "networking.k8s.io", "batch"]
    resources: ["pods", "pods/log", "services", "deployments", "statefulsets", "ingresses", "secrets", "configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vas-platform-rb
  namespace: team-b
subjects:
  - kind: ServiceAccount
    name: vas-platform-sa
    namespace: team-b
roleRef:
  kind: Role
  name: vas-platform-role
  apiGroup: rbac.authorization.k8s.io
